
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/database.types';

const SUPABASE_URL = "https://sqklqjvkroinzcjwmamv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxa2xxanZrcm9pbnpjandtYW12Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMjA3MjIsImV4cCI6MjA2MTU5NjcyMn0.nCMFET5hRFMzSJDFE5PPXLm68bihZm0o1kNEHY442L8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
